#!/usr/bin/env bash
#Short fix&sweet: configure a server running, and listening on port 80 of other
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo killall nginx
sudo service nginx restart
