#!/usr/bin/env bash
# Script that start in the terminal #0 and then killing it in the terminal #1

signal_msg()
{
	rm -f /var/run/myscript.pid
	exit
}

trap "echo 'I hate the kill command'; signal_msg" SIGTERM
trap "echo 'I hate the kill command'; signal_msg" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT

echo $$ >> /var/run/myscript.pid

while true
do
	echo 'To infinity and beyond'
	sleep 2
done
