#!/usr/bin/env bash
# Bash (init) script that manages another script

argv1=$1
mmp_pid="/var/run/my_process.pid"

iStart()
{
	./manage_my_process &
	echo "$!" > "$mmp_pid"
}

#  argument for stop/restart
iStop()
{
	sudo pkill -f "./manage_my_process"
	rm "$mmp_pid"
}
case "$argv1" in
	start) echo "manage_my_process started"
		iStart
		;;
	stop) echo "manage_my_process stopped"
		iStop
		;;
	restart) echo "manage_my_process restarted"
		iStop
		iStart
		;;

	#  if any other argument or no argument is passed
	*) echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
