#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

retval="/etc/passwd"

# loop for the bash script
while read file
do
	echo "$file" | cut -d ":" -f1,3,6
done < "$retval"
