#!/usr/bin/env bash
# Bash script that displays the content of the file using while loop + IFS.

retval="/etc/passwd"

# while loop with the format required
while IFS=":" read -r user gid homedir shell uid pw uinfo 
do
	echo "The user $user is part of the $gid gang, lives in $homedir and rides \
	$shell. $uid's place is protected by the passcode $pw, more info \
	about the user here: $uinfo"
done < "$retval"
