#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key

#establishuing the requirement for connection
HOST="100.26.155.154"
USER="ubuntu"
PRIVATE_KEY="~/.ssh/school"

# Connect to the server using SSH
ssh $PRIVATE_KEY $USER@$HOST
